function [plotOrder, plotNames, catColors] = getOctPlotInfo()
% GET OCT PLOT INFO - Get the ordering, reordering, and colors, for
% the October 2015 data.

% Give category names to each image, according to the order they were collected
patterns_sparse = 1:5;
gratings_sparse = 6:10;
noisebars_sparse = 11:15;
waves_sparse = 16:19; % the too-sparse wave stimulus has been removed, and there is one fewer
gratings_ori = [8, 20:22];
noisebars_ori = [13, 23:25];
waves_ori = [18, 26:28];
gratings_cross = [29, 30, 10, 31, 32, 8];
gratings_contrast = [33, 34, 8, 35, 36];
noisebars_contrast = [37, 38, 13, 39, 40];
waves_contrast = [41, 42, 18, 43, 44];
patterns_contrast = [46, 46, 3, 47, 48];

% Establish a canonical display order
plotOrder = [patterns_sparse, gratings_sparse, noisebars_sparse, waves_sparse, ...
             gratings_ori, noisebars_ori, waves_ori ...
             gratings_cross, ...
             patterns_contrast, gratings_contrast, noisebars_contrast, waves_contrast];
         
plotNames = [repmat({'patterns_sparse'}, length(patterns_sparse), 1); ...
 repmat({'gratings_sparse'}, length(gratings_sparse), 1); ...
 repmat({'noisebars_sparse'}, length(noisebars_sparse), 1); ...
 repmat({'waves_sparse'}, length(waves_sparse), 1); ...
 ...
 repmat({'gratings_ori'}, length(gratings_ori), 1); ...
 repmat({'noisebars_ori'}, length(noisebars_ori), 1); ...
 repmat({'waves_ori'}, length(waves_ori), 1); ...
 ...
 repmat({'gratings_cross'}, length(gratings_cross), 1); ...
 ...
 repmat({'patterns_contrast'}, length(patterns_contrast), 1); ...
 repmat({'gratings_contrast'}, length(gratings_contrast), 1); ...
 repmat({'noisebars_contrast'}, length(noisebars_contrast), 1); ...
 repmat({'waves_contrast'}, length(waves_contrast), 1)];

gratingsColor = [80, 130, 220] ./ 255; % blue
noisebarsColor = [120, 98, 86] ./ 255; % brown
wavesColor = [0, 115, 130] ./ 255; % green
patternsColor = [80, 40, 140] ./ 255; % purple

% not in plot order; needs to be reordered:
catColors = [repmat(patternsColor, length(patterns_sparse), 1); ...
 repmat(gratingsColor, length(gratings_sparse), 1); ...
 repmat(noisebarsColor, length(noisebars_sparse), 1); ...
 repmat(wavesColor, length(waves_sparse)+1, 1); ...
 ...
 repmat(gratingsColor, length(gratings_ori)-1, 1); ... % these -1 are to remove repeated categories
 repmat(noisebarsColor, length(noisebars_ori)-1, 1); ...
 repmat(wavesColor, length(waves_ori)-1, 1); ...
 ...
 repmat(gratingsColor, length(gratings_cross)-2, 1); ...
 ...
 repmat(gratingsColor, length(gratings_contrast)-1, 1); ...
 repmat(noisebarsColor, length(noisebars_contrast)-1, 1); ...
 repmat(wavesColor, length(waves_contrast)-1, 1); ...
 repmat(patternsColor, length(patterns_contrast)-1, 1)];