% stimuli.names = {'bw_vertical', ... % Stimulus set 1 = 69 stimuli, categories 1:3
%                   'bw_horizontal', ...
%                   'bw_central', ....
%                   'pattern_space', ... % Stimulus set 2 = 156 stimuli, categories 4:16
%                   'pattern_central', ...
%                   'grating_ori', ...
%                   'grating_contrast', ...
%                   'plaid_contrast', ...
%                   'circular_contrast', ...
%                   'pattern_contrast', ... % end of 99 dataset
%                   'non_geometric_small', ...
%                   'shapes', ...
%                   'scenes', ...
%                   'grating_sparse', ...
%                   'pattern_sparse', ...
%                     'noise_space', ...
%                   'noise_grating_halves', ...
%                   'natural'}; % Stimulus set 3 = 35 stimuli, category 17 only
% 
%     stimuli.numbers = {1:31, ...
%                     32:62, ...
%                     63:69, ...
%                     70:131, ...
%                     132:138, ...
%                     139:146, ...
%                     147:150, ...
%                     151:154, ...
%                     155:158, ...
%                     159:168, ...
%                     169:173, ...
%                     174, ... % this category has 7 per class, not 9
%                     175, ...
%                     176:180, ...
%                     181:184, ...
%                     185:208, ...
%                     209:225, ...
%                     226:260};
%                 
xNames = cell(155, 1);
start = 69;
xNames{70-start} = 'pattern_space';
xNames{132-start} = 'pattern_central';
xNames{139-start} = 'pattern_ori';
xNames{147-start} = 'grating_contrast';
xNames{151-start} = 'plaid_contrast';
xNames{155-start} = 'circular_contrast';
xNames{159-start} = 'pattern_contrast';
xNames{169-start} = 'non_geometric_small';
xNames{175-(start+1)} = 'scenes';
xNames{176-(start+1)} = 'grating_sparse';
xNames{181-(start+1)} = 'pattern_sparse';
xNames{185-(start+1)} = 'noise_space';
xNames{209-(start+1)} = 'noise_grating_halves';

figure; hold on;
bar(mean(betamnToUse, 1));
plot(mean(newPredictions, 2), 'go');
plot(mean(oldPredictions, 2), 'ro');
legend('data', 'new', 'old');

% xNames = strrep(xNames, '_', '\_');
set(gca,'XTick', 1:length(xNames), 'XTickLabel', xNames);
xticklabel_rotate([], 45);
xlabel('Stimulus category');
